"""initial_python_backend

Revision ID: 0001
Revises:
Create Date: 2026-09-18 14:47:35.587023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('entityId', sa.String(length=64), nullable=False),
    sa.Column('dedupeKey', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('availableAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lockedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupeKey')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('specialties',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('passwordHash', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('userId', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entityId', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_profiles',
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('licenseNumber', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photoUrl', sa.Text(), nullable=True),
    sa.Column('specialtyIds', sa.JSON(), nullable=False),
    sa.Column('requiresDeposit', sa.Boolean(), nullable=False),
    sa.Column('depositAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depositCurrency', sa.String(length=3), nullable=False),
    sa.Column('defaultSlotMinutes', sa.Integer(), nullable=False),
    sa.Column('cancellationWindowHours', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('icsFeedToken', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"cancellationWindowHours" >= 0'),
    sa.CheckConstraint('"defaultSlotMinutes" > 0'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icsFeedToken'),
    sa.UniqueConstraint('licenseNumber'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('notifications',
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('dedupeKey', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupeKey')
    )
    op.create_table('patient_profiles',
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('documentId', sa.String(length=64), nullable=True),
    sa.Column('birthDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('healthInsurance', sa.String(length=200), nullable=True),
    sa.Column('insuranceNumber', sa.String(length=100), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documentId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('refresh_tokens',
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('tokenHash', sa.String(length=64), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenHash')
    )
    op.create_index(op.f('ix_refresh_tokens_userId'), 'refresh_tokens', ['userId'], unique=False)
    op.create_table('appointments',
    sa.Column('patientId', sa.String(length=64), nullable=False),
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('startAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelledAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellationReason', sa.String(length=1000), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"endAt" > "startAt"'),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctorId'), 'appointments', ['doctorId'], unique=False)
    op.create_index(op.f('ix_appointments_patientId'), 'appointments', ['patientId'], unique=False)
    op.create_index(op.f('ix_appointments_startAt'), 'appointments', ['startAt'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('calendar_accounts',
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('externalEmail', sa.String(length=320), nullable=False),
    sa.Column('accessTokenEnc', sa.Text(), nullable=False),
    sa.Column('refreshTokenEnc', sa.Text(), nullable=False),
    sa.Column('tokenExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calendarId', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctorId', 'provider', 'externalEmail')
    )
    op.create_index(op.f('ix_calendar_accounts_doctorId'), 'calendar_accounts', ['doctorId'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.String(length=5), nullable=False),
    sa.Column('endTime', sa.String(length=5), nullable=False),
    sa.Column('slotMinutes', sa.Integer(), nullable=True),
    sa.Column('validFrom', sa.Date(), nullable=True),
    sa.Column('validTo', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"slotMinutes" IS NULL OR "slotMinutes" > 0'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6'),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedules_doctorId'), 'doctor_schedules', ['doctorId'], unique=False)
    op.create_table('locations',
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_doctorId'), 'locations', ['doctorId'], unique=False)
    op.create_table('medical_records',
    sa.Column('patientId', sa.String(length=64), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronicConditions', sa.Text(), nullable=True),
    sa.Column('currentMedication', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patientId')
    )
    op.create_table('oauth_states',
    sa.Column('tokenHash', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenHash')
    )
    op.create_table('schedule_overrides',
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startTime', sa.String(length=5), nullable=True),
    sa.Column('endTime', sa.String(length=5), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_overrides_doctorId'), 'schedule_overrides', ['doctorId'], unique=False)
    op.create_table('calendar_events',
    sa.Column('appointmentId', sa.String(length=64), nullable=False),
    sa.Column('accountId', sa.String(length=64), nullable=False),
    sa.Column('externalEventId', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['calendar_accounts.id'], ),
    sa.ForeignKeyConstraint(['appointmentId'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointmentId', 'accountId')
    )
    op.create_table('medical_record_entries',
    sa.Column('recordId', sa.String(length=64), nullable=False),
    sa.Column('doctorId', sa.String(length=64), nullable=False),
    sa.Column('appointmentId', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('amendsEntryId', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amendsEntryId'], ['medical_record_entries.id'], ),
    sa.ForeignKeyConstraint(['appointmentId'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['recordId'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_record_entries_recordId'), 'medical_record_entries', ['recordId'], unique=False)
    op.create_table('payments',
    sa.Column('appointmentId', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('preferenceId', sa.String(length=128), nullable=True),
    sa.Column('externalPaymentId', sa.String(length=128), nullable=True),
    sa.Column('checkoutUrl', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paidAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rawWebhookPayload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointmentId'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointmentId'),
    sa.UniqueConstraint('externalPaymentId')
    )
    op.create_table('attachments',
    sa.Column('entryId', sa.String(length=64), nullable=False),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('mimeType', sa.String(length=128), nullable=False),
    sa.Column('sizeBytes', sa.Integer(), nullable=False),
    sa.Column('storageKey', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entryId'], ['medical_record_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storageKey')
    )
    install_guards(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_medical_record_entries_recordId'), table_name='medical_record_entries')
    op.drop_table('medical_record_entries')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_schedule_overrides_doctorId'), table_name='schedule_overrides')
    op.drop_table('schedule_overrides')
    op.drop_table('oauth_states')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_locations_doctorId'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_doctor_schedules_doctorId'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_calendar_accounts_doctorId'), table_name='calendar_accounts')
    op.drop_table('calendar_accounts')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_startAt'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patientId'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctorId'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_refresh_tokens_userId'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('patient_profiles')
    op.drop_table('notifications')
    op.drop_table('doctor_profiles')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS reject_immutable_change()")
    # ### end Alembic commands ###


def install_guards(connection):
    if connection.dialect.name == "postgresql":
        connection.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS btree_gist")
        connection.exec_driver_sql("""ALTER TABLE appointments ADD CONSTRAINT appointments_no_overlap
            EXCLUDE USING gist ("doctorId" WITH =, tstzrange("startAt", "endAt", '[)') WITH &&)
            WHERE (status IN ('CONFIRMED', 'PENDING_PAYMENT'))""")
        connection.exec_driver_sql("""CREATE FUNCTION reject_immutable_change() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN RAISE EXCEPTION 'append-only table'; END; $$""")
        for table in ("medical_record_entries", "audit_logs"):
            connection.exec_driver_sql(f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_immutable_change()")
    else:
        for operation in ("INSERT", "UPDATE"):
            connection.exec_driver_sql(f"""CREATE TRIGGER appointments_overlap_{operation.lower()}
                BEFORE {operation} ON appointments WHEN NEW.status IN ('CONFIRMED', 'PENDING_PAYMENT')
                BEGIN SELECT RAISE(ABORT, 'appointment overlap') WHERE EXISTS (
                    SELECT 1 FROM appointments a WHERE a."doctorId" = NEW."doctorId"
                    AND a.id != NEW.id AND a.status IN ('CONFIRMED', 'PENDING_PAYMENT')
                    AND a."startAt" < NEW."endAt" AND a."endAt" > NEW."startAt"); END""")
        for table in ("medical_record_entries", "audit_logs"):
            for operation in ("UPDATE", "DELETE"):
                connection.exec_driver_sql(f"CREATE TRIGGER immutable_{table}_{operation.lower()} BEFORE {operation} ON {table} BEGIN SELECT RAISE(ABORT, 'append-only table'); END")
